console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[secondary_prompt]
  template = ' ᗌ '
  foreground = 'lightWhite'
  background = 'transparent'

[transient_prompt]
  template = 'ᗌ '
  background = 'transparent'
  foreground_templates = ['{{ if gt .Code 0 }}#ee8800{{ end }}', '{{ if eq .Code 0 }}white{{ end }}']

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = '{{ .FormattedMs }}'
    foreground = 'white'
    background = 'blue'
    type = 'executiontime'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    leading_diamond = ''
    template = '  {{ .Path }} '
    foreground = 'black'
    background = 'red'
    type = 'path'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

  [[blocks.segments]]
    template = '{{ if .Segments.Contains "Git" }}{{ else }}{{ end }}'
    foreground = 'red'
    background = 'transparent'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    leading_diamond = '<transparent,background></>'
    trailing_diamond = ''
    template = ' {{ .HEAD }} '
    foreground = 'black'
    type = 'git'
    style = 'diamond'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}yellow{{ end }}', 'green']

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = ' ᗌ'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}#ee8800{{ end }}', '{{ if eq .Code 0 }}lightWhite{{ end }}']

    [blocks.segments.properties]
      cache_duration = 'none'
